//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protofile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammerSkill
    {
        public int IDProgrammerSkills { get; set; }
        public int IdSkills { get; set; }
        public int IdProgrammers { get; set; }
        public int expert { get; set; }
        public byte[] cretificate { get; set; }
    
        public virtual Programmer Programmer { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
